services:
  capital-consultancy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capital_consultancy_app
    restart: unless-stopped
    ports:
      - "3335:80"
    networks:
      - capital_consultancy_network

networks:
  capital_consultancy_network:
    driver: bridge